In [16]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("../data/sales_data.xls")

In [8]:
df = df.sort_values(
    ["Store ID", "Product ID", "Date"]
)
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
100,2022-01-02,S001,P0001,Electronics,North,93,71,0,65.63,5,Snowy,0,73.66,Winter,0,84
200,2022-01-03,S001,P0001,Electronics,North,274,142,229,68.55,15,Snowy,1,80.73,Winter,0,132
300,2022-01-04,S001,P0001,Electronics,North,132,42,0,61.66,10,Snowy,0,54.88,Winter,0,67
400,2022-01-05,S001,P0001,Electronics,North,319,129,0,59.56,25,Snowy,1,57.34,Winter,0,110

Demand Lags

In [10]:
group_cols = ["Store ID", "Product ID"]

df["Demand_Lag_1"] = (
    df.groupby(group_cols)["Demand"]
    .shift(1)
)

df["Demand_Lag_7"] = (
    df.groupby(group_cols)["Demand"]
    .shift(7)
)

df["Demand_Lag_30"] = (
    df.groupby(group_cols)["Demand"]
    .shift(30)
)

df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand,Demand_Lag_1,Demand_Lag_7,Demand_Lag_30
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115,NaN,NaN,NaN
100,2022-01-02,S001,P0001,Electronics,North,93,71,0,65.63,5,Snowy,0,73.66,Winter,0,84,115.0,NaN,NaN
200,2022-01-03,S001,P0001,Electronics,North,274,142,229,68.55,15,Snowy,1,80.73,Winter,0,132,84.0,NaN,NaN
300,2022-01-04,S001,P0001,Electronics,North,132,42,0,61.66,10,Snowy,0,54.88,Winter,0,67,132.0,NaN,NaN
400,2022-01-05,S001,P0001,Electronics,North,319,129,0,59.56,25,Snowy,1,57.34,Winter,0,110,67.0,NaN,NaN

Price lag

In [11]:
df["Price_Lag_1"] = (
    df.groupby(group_cols)["Price"]
    .shift(1)
)
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand,Demand_Lag_1,Demand_Lag_7,Demand_Lag_30,Price_Lag_1
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115,NaN,NaN,NaN,NaN
100,2022-01-02,S001,P0001,Electronics,North,93,71,0,65.63,5,Snowy,0,73.66,Winter,0,84,115.0,NaN,NaN,72.72
200,2022-01-03,S001,P0001,Electronics,North,274,142,229,68.55,15,Snowy,1,80.73,Winter,0,132,84.0,NaN,NaN,65.63
300,2022-01-04,S001,P0001,Electronics,North,132,42,0,61.66,10,Snowy,0,54.88,Winter,0,67,132.0,NaN,NaN,68.55
400,2022-01-05,S001,P0001,Electronics,North,319,129,0,59.56,25,Snowy,1,57.34,Winter,0,110,67.0,NaN,NaN,61.66

Rolling demand mean

In [12]:
df["Demand_Mean_7"] = (
    df.groupby(group_cols)["Demand"]
    .transform(
        lambda x: x.rolling(7).mean()
    )
)

df["Demand_Mean_30"] = (
    df.groupby(group_cols)["Demand"]
    .transform(
        lambda x: x.rolling(30).mean()
    )
)

df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,...,Competitor Pricing,Seasonality,Epidemic,Demand,Demand_Lag_1,Demand_Lag_7,Demand_Lag_30,Price_Lag_1,Demand_Mean_7,Demand_Mean_30
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,...,85.73,Winter,0,115,NaN,NaN,NaN,NaN,NaN,NaN
100,2022-01-02,S001,P0001,Electronics,North,93,71,0,65.63,5,...,73.66,Winter,0,84,115.0,NaN,NaN,72.72,NaN,NaN
200,2022-01-03,S001,P0001,Electronics,North,274,142,229,68.55,15,...,80.73,Winter,0,132,84.0,NaN,NaN,65.63,NaN,NaN
300,2022-01-04,S001,P0001,Electronics,North,132,42,0,61.66,10,...,54.88,Winter,0,67,132.0,NaN,NaN,68.55,NaN,NaN
400,2022-01-05,S001,P0001,Electronics,North,319,129,0,59.56,25,...,57.34,Winter,0,110,67.0,NaN,NaN,61.66,NaN,NaN

Rolling demand volatility

In [13]:
df["Demand_Std_7"] = (
    df.groupby(group_cols)["Demand"]
    .transform(
        lambda x: x.rolling(7).std()
    )
)

df["Demand_Std_30"] = (
    df.groupby(group_cols)["Demand"]
    .transform(
        lambda x: x.rolling(30).std()
    )
)

df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,...,Epidemic,Demand,Demand_Lag_1,Demand_Lag_7,Demand_Lag_30,Price_Lag_1,Demand_Mean_7,Demand_Mean_30,Demand_Std_7,Demand_Std_30
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,...,0,115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,2022-01-02,S001,P0001,Electronics,North,93,71,0,65.63,5,...,0,84,115.0,NaN,NaN,72.72,NaN,NaN,NaN,NaN
200,2022-01-03,S001,P0001,Electronics,North,274,142,229,68.55,15,...,0,132,84.0,NaN,NaN,65.63,NaN,NaN,NaN,NaN
300,2022-01-04,S001,P0001,Electronics,North,132,42,0,61.66,10,...,0,67,132.0,NaN,NaN,68.55,NaN,NaN,NaN,NaN
400,2022-01-05,S001,P0001,Electronics,North,319,129,0,59.56,25,...,0,110,67.0,NaN,NaN,61.66,NaN,NaN,NaN,NaN

Rolling max

In [14]:
df["Demand_Max_7"] = (
    df.groupby(group_cols)["Demand"]
    .transform(
        lambda x: x.rolling(7).max()
    )
)
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,...,Demand,Demand_Lag_1,Demand_Lag_7,Demand_Lag_30,Price_Lag_1,Demand_Mean_7,Demand_Mean_30,Demand_Std_7,Demand_Std_30,Demand_Max_7
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,...,115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,2022-01-02,S001,P0001,Electronics,North,93,71,0,65.63,5,...,84,115.0,NaN,NaN,72.72,NaN,NaN,NaN,NaN,NaN
200,2022-01-03,S001,P0001,Electronics,North,274,142,229,68.55,15,...,132,84.0,NaN,NaN,65.63,NaN,NaN,NaN,NaN,NaN
300,2022-01-04,S001,P0001,Electronics,North,132,42,0,61.66,10,...,67,132.0,NaN,NaN,68.55,NaN,NaN,NaN,NaN,NaN
400,2022-01-05,S001,P0001,Electronics,North,319,129,0,59.56,25,...,110,67.0,NaN,NaN,61.66,NaN,NaN,NaN,NaN,NaN

All other useful statistics

In [17]:
df["Revenue"] = df["Units Sold"] * df["Price"] * (1 - (df["Discount"] / 100))
df["Inventory Value"] = df["Inventory Level"] * df["Price"]
df["Lost Demand"] = np.maximum(df["Demand"] - df["Units Sold"], 0)
df["Stockout"] = df["Inventory Level"] < df["Demand"]
df["Overstock"] = df["Inventory Level"] > (2 * df["Demand"])
df["Sell Through Rate"] = df["Units Sold"] / np.maximum(df["Inventory Level"], 1)
df["Inventory Turnover"] = df["Units Sold"] / np.maximum(df["Inventory Level"], 1)
df["Coverage Days"] = df["Inventory Level"] / np.maximum(df["Demand"], 1)
df["Price Gap"] = df["Price"] - df["Competitor Pricing"]
df["Gross Profit (Proxy)"] = df["Revenue"] - (df["Units Sold"] * df["Price"] * 0.4)

df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,...,Revenue,Inventory Value,Lost Demand,Stockout,Overstock,Sell Through Rate,Inventory Turnover,Coverage Days,Price Gap,Gross Profit (Proxy)
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,...,7046.5680,14180.40,13,False,False,0.523077,0.523077,1.695652,-13.01,4079.5920
100,2022-01-02,S001,P0001,Electronics,North,93,71,0,65.63,5,...,4426.7435,6103.59,13,False,False,0.763441,0.763441,1.107143,-8.03,2562.8515
200,2022-01-03,S001,P0001,Electronics,North,274,142,229,68.55,15,...,8273.9850,18782.70,0,False,True,0.518248,0.518248,2.075758,-12.18,4380.3450
300,2022-01-04,S001,P0001,Electronics,North,132,42,0,61.66,10,...,2330.7480,8139.12,25,False,False,0.318182,0.318182,1.970149,6.78,1294.8600
400,2022-01-05,S001,P0001,Electronics,North,319,129,0,59.56,25,...,5762.4300,18999.64,0,False,True,0.404389,0.404389,2.900000,2.22,2689.1340

RAG Embeddings

In [19]:
df["rag_text"] = (
    "Date: " + df["Date"].astype(str)
    + ". Store: " + df["Store ID"].astype(str)
    + ". Product: " + df["Product ID"].astype(str)
    + ". Category: " + df["Category"].astype(str)
    + ". Region: " + df["Region"].astype(str)
    + ". Demand: " + df["Demand"].astype(str)
    + ". Units Sold: " + df["Units Sold"].astype(str)
    + ". Inventory: " + df["Inventory Level"].astype(str)
    + ". Price: " + df["Price"].astype(str)
    + ". Discount: " + df["Discount"].astype(str)
    + ". Promotion: " + df["Promotion"].astype(str)
    + ". Weather: " + df["Weather Condition"].astype(str)
    + ". Seasonality: " + df["Seasonality"].astype(str)
    + ". Epidemic: " + df["Epidemic"].astype(str)
)
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,...,Inventory Value,Lost Demand,Stockout,Overstock,Sell Through Rate,Inventory Turnover,Coverage Days,Price Gap,Gross Profit (Proxy),rag_text
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,...,14180.40,13,False,False,0.523077,0.523077,1.695652,-13.01,4079.5920,Date: 2022-01-01. Store: S001. Product: P0001....
100,2022-01-02,S001,P0001,Electronics,North,93,71,0,65.63,5,...,6103.59,13,False,False,0.763441,0.763441,1.107143,-8.03,2562.8515,Date: 2022-01-02. Store: S001. Product: P0001....
200,2022-01-03,S001,P0001,Electronics,North,274,142,229,68.55,15,...,18782.70,0,False,True,0.518248,0.518248,2.075758,-12.18,4380.3450,Date: 2022-01-03. Store: S001. Product: P0001....
300,2022-01-04,S001,P0001,Electronics,North,132,42,0,61.66,10,...,8139.12,25,False,False,0.318182,0.318182,1.970149,6.78,1294.8600,Date: 2022-01-04. Store: S001. Product: P0001....
400,2022-01-05,S001,P0001,Electronics,North,319,129,0,59.56,25,...,18999.64,0,False,True,0.404389,0.404389,2.900000,2.22,2689.1340,Date: 2022-01-05. Store: S001. Product: P0001....

Handling missing values

In [20]:
df = df.fillna(0)

test and train split

In [23]:
df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date").reset_index(drop=True)

split_idx = int(len(df) * 0.8)

train_df = df.iloc[:split_idx]
test_df = df.iloc[split_idx:]

print(train_df["Date"].min())
print(train_df["Date"].max())

print(test_df["Date"].min())
print(test_df["Date"].max())

2022-01-01 00:00:00
2023-06-09 00:00:00
2023-06-09 00:00:00
2023-10-18 00:00:00

Making train and test csv files

In [24]:
train_df.to_csv("train_data.csv", index=False)
test_df.to_csv("test_data.csv", index=False)

Saving fully feature engineered dataframe

In [25]:
df.to_csv("processed_sales_data.csv", index=False)